// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZgMHMqQqv8hwg57YYvgDdHv89B0WTII',
    appId: '1:326111149249:web:81c62cfe7a40318616a840',
    messagingSenderId: '326111149249',
    projectId: 'ev-charging-locator-57df6',
    authDomain: 'ev-charging-locator-57df6.firebaseapp.com',
    storageBucket: 'ev-charging-locator-57df6.appspot.com',
    measurementId: 'G-6ZJ16YH0PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1J6raMvGPm4HNJsGt58ler7ZybIBqz4',
    appId: '1:326111149249:android:0db75b0ab545372316a840',
    messagingSenderId: '326111149249',
    projectId: 'ev-charging-locator-57df6',
    storageBucket: 'ev-charging-locator-57df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAItzcmnxboZivN7j3k4YkxCiC1tPX4BJY',
    appId: '1:326111149249:ios:19354b0e5f7392dc16a840',
    messagingSenderId: '326111149249',
    projectId: 'ev-charging-locator-57df6',
    storageBucket: 'ev-charging-locator-57df6.appspot.com',
    iosBundleId: 'com.kazungudev.evChargingLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAItzcmnxboZivN7j3k4YkxCiC1tPX4BJY',
    appId: '1:326111149249:ios:bd8df972f24d1f8516a840',
    messagingSenderId: '326111149249',
    projectId: 'ev-charging-locator-57df6',
    storageBucket: 'ev-charging-locator-57df6.appspot.com',
    iosBundleId: 'com.kazungudev.evChargingLocator.RunnerTests',
  );
}
